<script setup lang="ts">
// types
import type { Project } from '@/types'

/**
 * page metadata
 * ================================================================
 */
useHead({
  title: "Create Turborepo (vue-nuxt:docs)",
  meta: [{ name: "description", content: "Generated by create turbo" }],
});

/**
 * data fetching
 * ================================================================
 */
const query = groq`*[_type == "project"]`
const { data } = useSanityQuery<Project>(query)

</script>

<template>
  <h1>
    {{ data }}
  </h1>
</template>
